// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCITzKtpSGO9Thplwy8lODiNjEsw0oU7BA',
    appId: '1:414803736102:web:ba2f373b15df80ce4f58e7',
    messagingSenderId: '414803736102',
    projectId: 'heart-rate-monitoring-app1',
    authDomain: 'heart-rate-monitoring-app1.firebaseapp.com',
    storageBucket: 'heart-rate-monitoring-app1.appspot.com',
    measurementId: 'G-B43BE7TX6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfmnv_mLLDlv_nHp6bvaMKBew1Fm5fM44',
    appId: '1:414803736102:android:3f98af9f3aab66244f58e7',
    messagingSenderId: '414803736102',
    projectId: 'heart-rate-monitoring-app1',
    storageBucket: 'heart-rate-monitoring-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2gtyqjEayofs0AN35mUkIWt_ZO_vSgEY',
    appId: '1:414803736102:ios:fe064c7c68f9996e4f58e7',
    messagingSenderId: '414803736102',
    projectId: 'heart-rate-monitoring-app1',
    storageBucket: 'heart-rate-monitoring-app1.appspot.com',
    iosBundleId: 'com.example.heartRateMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2gtyqjEayofs0AN35mUkIWt_ZO_vSgEY',
    appId: '1:414803736102:ios:fe064c7c68f9996e4f58e7',
    messagingSenderId: '414803736102',
    projectId: 'heart-rate-monitoring-app1',
    storageBucket: 'heart-rate-monitoring-app1.appspot.com',
    iosBundleId: 'com.example.heartRateMonitorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCITzKtpSGO9Thplwy8lODiNjEsw0oU7BA',
    appId: '1:414803736102:web:f3846e554802d60f4f58e7',
    messagingSenderId: '414803736102',
    projectId: 'heart-rate-monitoring-app1',
    authDomain: 'heart-rate-monitoring-app1.firebaseapp.com',
    storageBucket: 'heart-rate-monitoring-app1.appspot.com',
    measurementId: 'G-JBJGLD14R5',
  );
}
